name: Build Workflow

on:
  workflow_call:

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseImage: ['nvcr.io/nvidia/tritonserver']
        baseTag: ['23.08']
    steps:
      - name: Trigger Manually Triggered Build and Push Workflow
        uses: ./.github/workflows/build.yml # Ensure this references the correct path and branch
        with:
          baseImage: ${{ matrix.baseImage }}
          baseTag: ${{ matrix.baseTag }}
