name: Manually Triggered Build and Push

on:
  workflow_call:
    inputs:
      baseImage:
        description: 'Base image (e.g., nvcr.io/nvidia/tritonserver)'
        required: true
        default: 'nvcr.io/nvidia/tritonserver'
      baseTag:
        description: 'Base image tag (e.g., 24.01-py3-igpu)'
        required: true
        default: '24.01-py3-igpu'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/tritonserver-custom:${{ github.event.inputs.baseTag }}
          build-args: |
            BASE_IMAGE=${{ github.event.inputs.baseImage }}
            BASE_TAG=${{ github.event.inputs.baseTag }}
