name: Combined Build and Push on Push Trigger

on:
  push: # This triggers the workflow on every push to the repository.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseImage: ['nvcr.io/nvidia/tritonserver'] # Define your base images here
        baseTag: ['23.08'] # Define the base tags here
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/tritonserver-custom:${{ matrix.baseTag }}
          build-args: |
            BASE_IMAGE=${{ matrix.baseImage }}
            BASE_TAG=${{ matrix.baseTag }}

