name: Release Workflow

on:
  push:
    branches:
      - main # Adjust this to match your release branch or triggering condition

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseImage: ['nvcr.io/nvidia/tritonserver']
        baseTag: ['23.08']
    steps:
      - name: Trigger Manually Triggered Build and Push Workflow
        uses: ./.github/workflows/build.yml@main # Ensure this references the correct path and branch
        with:
          baseImage: ${{ matrix.baseImage }}
          baseTag: ${{ matrix.baseTag }}
